# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Circle": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jami-sk.github.io/ExploratoryProgramming/"

git_url = "https://github.com/jami-sk/ExploratoryProgramming/tree/master/"

def custom_doc_links(name): return None
